version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"
    HUGO_VERSION: "0.53"
    HUGO_SHA256: "0e4424c90ce5c7a0c0f7ad24a558dd0c2f1500256023f6e3c0004f57a20ee119"

phases:
  install:
    commands:
      - git clone https://github.com/blquinn/hugoblog.git --recursive
  build:
    commands:
      - (cd hugoblog && hugo && python3 sync.py)
