baseURL = "https://blq.me/"
languageCode = "en-us"
title = "braindamage"
theme = "braindamage"

[markup]
  [markup.highlight]
  style = "swapoff"

[deployment]
[[deployment.targets]]
name = "aws"
URL = "s3://bquinn-hugoblog?region=us-east-1"
cloudFrontDistributionID = "ECH433SQB2WMU"
cacheControl = "max-age=3600, no-transform, public"
gzip = true
