baseURL = "https://blq.me/"
languageCode = "en-us"
title = "braindamage"
theme = "braindamage"


[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Categories'
  pageRef = '/categories'
  weight = 20
[[menu.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 30

[markup]
[markup.highlight]
style = "swapoff"

[deployment]
[[deployment.targets]]
name = "aws"
URL = "s3://bquinn-hugoblog?region=us-east-1"
cloudFrontDistributionID = "ECH433SQB2WMU"
cacheControl = "max-age=3600, no-transform, public"
gzip = true
